[package]
name = "boilerplate"
version = "0.1.0"
authors = ["colinfruit <17092461+colinfruit@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"

